distributed:
    admin:
        tick:
            interval: 500ms # time between event loop health checks
            limit: 2h # time allowed between triggering a warning

    comm:
        retry:
            count: 10

        timeouts:
            connect: 600s

    scheduler:
        allowed-failures: 5 # default 3
        worker-ttl: 120s # default 5min

        locks:
            lease-timeout: 900s
            lease-validation-interval: 300s

    worker:
        use-file-locking: False

        memory:
            transfer: 0.2 # default 0.1
            target: 0.9 # default 0.6
            spill: 0.9 # default 0.7
            pause: false # default 0.8
            terminate: false # default 0.95
            recent-to-old-time: 1h
            monitor-interval: 500ms # default 100ms

        profile:
            interval: 50ms # default 10ms
